on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Image Tag'
        required: true
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        type: string
      node_version:
        description: 'Node Version'
        required: true
        type: string
jobs:
  deploy_documentation:
    name: Deploy Documentation
    runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v3
