name: On Push
on:
  push:
    branches:
      - main

jobs:
  deploy_documentation_nonlive:
    name: Deploy Documentation - Nonlive
    uses: ./.github/workflows/deploy.yml
    with:
      environment: nonlive
      image_tag: snapshot_${{ github.sha }}
      node_version: 16
