name: GH code
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy'
        required: false
        default: 'latest'
        type: string
jobs:
  docker_digest:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
      - name: Get latest image digest
        id: docker
        run: |
          docker_digets=$(curl https://registry.hub.docker.com/v2/repositories/ottoopensource/b2bds-docs/tags | jq -r --arg TAG "$TAG" '.results[] | select(.name == $TAG) | .digest')
          echo "digest=$docker_digets" >> "$GITHUB_OUTPUT"
        env:
          TAG: ${{ inputs.tag }}
  job2:
    runs-on: ubuntu-latest
    needs: docker_digest
    steps:
      - env:
          OUTPUT2: ${{needs.docker_digest.outputs.digest}}
        run: echo "$OUTPUT2"
