name: GH code
on:
  workflow_dispatch:

jobs:
  docker_digest:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output2: ${{ steps.docker.outputs.digest }}
    steps:
      - name: Get latest image digest
        id: docker
        run: |
          response=$(curl https://registry.hub.docker.com/v2/repositories/ottoopensource/b2bds-docs/tags | jq -r '.results[0].digest')
          echo "response from curl= $response"
          echo "digest=$response" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT2"
