name: Manual Trigger
on:
  workflow_dispatch:

jobs:
  docker_digest:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
      - name: Get latest image digest
        id: docker
        run: |
          echo "digest=$(curl https://registry.hub.docker.com/v2/repositories/ottoopensource/b2bds-docs/tags | jq -r '.results[0].digest')" >> $GITHUB_OUTPUT

  test_output:
    runs-on: ubuntu-latest
    needs: docker_digest
    steps:
      - env:
          OUTPUT1: ${{needs.docker.outputs.digest}}
        run: echo "$OUTPUT1"
