name: Manual Trigger
on:
  workflow_dispatch:

jobs:
  docker_digest:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy resources
        run: |
          curl https://registry.hub.docker.com/v2/repositories/ottoopensource/b2bds-docs/tags
