name: Manual Trigger
on:
  workflow_dispatch:

jobs:
  docker_digest:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.docker.outputs.digest }}
    steps:
      - name: Get latest image digest
        id: docker
        run: |
          response=$(curl https://registry.hub.docker.com/v2/repositories/ottoopensource/b2bds-docs/tags | jq -r '.results[0].digest')"
          echo "response from curl= $response"  
          echo "digest=$response" >> "$GITHUB_OUTPUT"

  test_output:
    runs-on: ubuntu-latest
    needs: docker_digest
    steps:
      - env:
          OUTPUT1: ${{needs.docker.outputs.output1}}
        run: echo "$OUTPUT1"
